file_read = open("2nd.txt", 'r')
print(file_read.read())
file_read.close()
file_write = open("2nd.txt", 'w')
file_write.write('My favorite subject is maths')
file_write.close()
file_append= open("2nd.txt", 'a')
file_append.write('\nI am also learning coding')
file_append.close()
